version: 2.1
jobs:
    build_and_test:
        working_directory: ~/app
        docker:
            - image: vdtn359/news-ci
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install node_modules
                  command: |
                      npm set verify-store-integrity false
                      pnpm recursive install --unsafe-perm
            - save_cache:
                  key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - ~/.pnpm-store
            - restore_cache:
                  key: next-cache
            - run:
                  name: Build
                  command: pnpm run cli -- build
            - save_cache:
                  key: next-cache
                  paths:
                      - app/web/.next/cache
            - run:
                  name: Test
                  command: npx jest
    deploy_aws:
        working_directory: ~/app
        docker:
            - image: vdtn359/news-ci
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install node_modules
                  command: |
                      npm set verify-store-integrity false
                      pnpm recursive install --unsafe-perm
            - save_cache:
                  key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - ~/.pnpm-store
            - run:
                  name: Build crawler
                  command: cd app/crawler && npm run package
            - run:
                  name: Deploy crawler
                  command: make provisionCrawler
            - run:
                  name: Build scheduler
                  command: cd app/scheduler && npm run package
            - run:
                  name: Deploy scheduler
                  command: make provisionScheduler
workflows:
    version: 2
    build_and_test:
        jobs:
            - build_and_test
            - hold_aws:
                  type: approval
                  requires:
                      - build_and_test
            - deploy_aws:
                  requires:
                      - hold_aws
